### ISSUE TITLE
Through GUI possible?

### ISSUE THREAD

**Issue by worldsdream** [mustaphaturhan/linkedin-delete-applied-jobs#1]
Great stuff. I have not yet tested it. Is it possible to remove applied jobs through LinkedIn website or do we really have to use this software you made?

**Comment by mustaphaturhan** [comment]
@worldsdream it is possible actually.
- Go to [LinkedIn Jobs](https://www.linkedin.com/jobs/)
- Find a button called ["Track my jobs"](https://www.linkedin.com/jobs/tracker/saved/) and click that.
- You should see two tabs, one is "saved," and other one is "applied." Click applied.

Now you should see every job that you apply.

There is a shorter way. You can click here: https://www.linkedin.com/jobs/tracker/applied/.

**Comment by worldsdream** [comment]
Thanks! Worked as described. Perfect answer.
